# Generated by Django 3.1.6 on 2021-02-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=30)),
                ('duration', models.PositiveSmallIntegerField()),
                ('recorded_time', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[(0, 'Pendiente'), (1, 'Completada')], default=0, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
