# Generated by Django 3.1.6 on 2021-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210217_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='recorded_time',
            field=models.PositiveSmallIntegerField(default=50),
            preserve_default=False,
        ),
    ]
