# Generated by Django 3.1.6 on 2021-02-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_todo_recorded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='recorded_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
